package com.demo.webrtc.models

data class UserInfo(
        var about_me: String,
        var age: Int,
        var city: String,
        var city_id: String? = null,
        var country: String,
        var country_id: String,
        var denomination: Int,
        var denomination_title: String?,
        var dob: String,
        var is_notification: Int,
        var referral_code: String,
        var reward_point: Int,
        var plan_id: Int,
        var dressing: String,
        var plan_icon: String,
        var dressing_title: List<String>? = null,
        var drinks: String,
        var education: String,
        var education_title: String? = null,
        var email: String,
        var ethnicity: String,
        var ethnicity_SelectedTitle: String? = null,
        var food: String? = null,
        var food_title: String? = null,
        var gender: String,
        var height_in_centemeter: Int,
        var id: Int,
        var image1: String? = null,
        var image2: String? = null,
        var image3: String? = null,
        var image4: String? = null,
        var kids: Int,
        var kids_title: String? = null,
        var language: String,
        var language_titles: List<String>?,
        var when_to_marry_age_title: String? = "",
        var lat: String,
        var long: String,
        var marital_status: Int,
        var marital_status_title: String?,
        var mob_no: String,
        var country_code: Int,
        var religion: Int,
        var religion_title: String? = null,
        var smoking: String,
        var state: String,
        var state_id: String,
        var username: String,
        var first_name: String?,
        var last_name: String?,
        var when_to_marry_age: String? = null,
        var profession: String,
        var profession_titles: String? = null,
        var country_flag: String,
        var authToken: String,
        var otp: String,
        var weight: Int,
        var is_selfie_verify: Int,
        var is_profile_update: Int,
        var is_profile_completed: Int,
        var is_verify: Int,
        var is_social_login: String,
        var wali: String,
        var fb_social_id: Int,
        var nationality_id: String? = "",
        var social_id: String? = "",
        var nationality_title: String? = "",
        var background_theme: String? = "",
        var plan_purchase: Int
) {
    val full_name: String
        get() = buildString {
            append(first_name)
            if(!last_name.isNullOrEmpty()) append(" $last_name")
        }
}


